services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb123
      - MYSQL_DATABASE=afinidatadb
      - MYSQL_USER=userafinidata
      - MYSQL_PASSWORD=passwordafinidata
    ports:
      - "3306:3306"
