version: '2.2'

networks:
  my_network:
    driver: bridge

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=afinidatadb
      - MYSQL_USER=usermysql
      - MYSQL_PASSWORD=passwordmysql
    ports:
      - "3306:3306"
    networks:
      - my_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - my_network
